# Generated by Django 6.0.1 on 2026-01-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zip_code',
            field=models.IntegerField(max_length=10),
        ),
    ]
