# Generated by Django 6.0.1 on 2026-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_record_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zip_code',
            field=models.TextField(max_length=100),
        ),
    ]
