# Generated by Django 6.0.1 on 2026-01-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_record_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
