# Generated by Django 6.0.1 on 2026-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_zip_code_record_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='zip_code',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
